# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "kameshsampath/EnvoyBuilder"
  
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.define "EnvoyBuilder" do |node|
    node.vm.provision "shell", path: "scripts/build_envoy.sh"
    node.vm.provider "virtualbox" do |vb|
        vb.name   = "EnvoyBuilder"
        vb.memory = 2048 
        vb.cpus   = 2
    end
  end

end
